package:
  name: "gallop"
  version: "0.1.3"

source:
  path: .

requirements:
  host:
    - python
  build:
    - python
  run:
    - python>=3.8*
    - streamlit
    - pytorch=1.12.1
    - scipy>=1.7*
    - py3dmol=1.7*
    - torch-optimizer=0.1.0
    - pymatgen
    - cudatoolkit 11.6*
    - mpld3


about:
  home: https://github.com/mspillman/gallop
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: "Fast crystal structure determination from powder diffraction data"