package:
  name: "gallop"
  version: "0.1.0"

source:
  path: .

requirements:
  host:
    - python
  build:
    - python
  run:
    - python>=3.8*
    - streamlit=0.89.0
    - pytorch=1.9.1
    - scipy>=1.7*
    - py3dmol
    - torch-optimizer
    - tqdm
    - pymatgen=2021.2.8.1
    
    

about:
  home: https://github.com/mspillman/gallop
  license: GPLv3
  license_familY: GPL
  license_file: LICENSE
  summary: "Fast crystal structure determination from powder diffraction data"